Class SF_Player : DoomPlayer
{
	Default
	{
		Speed 15.5;
		Player.ViewBob 0.75;
		Player.TeleportFreezeTime 6;
		Friction 0.85;
		Player.DisplayName "Karl";
		Player.StartItem "SF_Axe";
		Player.Jumpz 9;
		Player.WeaponSlot 0, "SF_WallJumpWeapon";
		Player.WeaponSlot 1, "SF_Axe", "SF_RipSaw";
		Player.WeaponSlot 2, "SF_NOVA";
		Player.WeaponSlot 3, "SF_Slugger", "SF_Dominatus";
		Player.WeaponSlot 4, "SF_Viper";
		Player.WeaponSlot 5, "SF_SpeedHucker";
	}

	bool isUsing;
	bool isWallAttached;
	Vector3 wallAttachPos; // Store the position where the player attached

	bool didDeathCam;
	int deathCamTics;

	double wobbleDir;
	double targetPitch;
	double targetYaw;
	double targetRoll;


	override void Tick()
	{
		super.Tick();

		if (player.cmd.buttons & BT_USE)
		{
			if (!isUsing)
			{
				if (!isWallAttached)
				{
					// Robust wall scan using FLineTraceData
					FLineTraceData LedgeTrace;
					double TraceDistance = sqrt(2) * Radius + 1;
					LineTrace(angle, TraceDistance, 0, TRF_BLOCKSELF|TRF_THRUACTORS, Height * 1.2, data: LedgeTrace);

					if (LedgeTrace.HitType == TRACE_HitWall)
					{
						// Check wall texture
						if (LedgeTrace.HitTexture == TexMan.CheckForTexture("WALLJUMP", TexMan.Type_Wall))
						{
							isWallAttached = true;
							wallAttachPos = pos; // Store current position
							vel = (0, 0, 0); // Freeze movement
						}
					}
				}
				else
				{
					// Launch off wall
					isWallAttached = false;
					Vector2 jumpDir2 = AngleToVector(angle);
					double jumpStrength = 24.0;
					vel = (jumpDir2.x * jumpStrength, jumpDir2.y * jumpStrength, JumpZ * 1.25);
				}
			}
			isUsing = true;
		}
		else
		{
			isUsing = false;
		}

		// If attached to wall, freeze player position and check distance
		if (isWallAttached)
		{
			vel = (0, 0, 0);
			if ((pos - wallAttachPos).Length() > 8)
			{
				isWallAttached = false;
			}
		}

		// Trigger once
		if (health <= 0 && player && !didDeathCam)
		{
			StartDeathCam();
			Vector2 back = -AngleToVector(angle);
			vel.x += back.x * 32.0;
			vel.y += back.y * 32.0;
		}

		// Death camera sequence
		if (didDeathCam && player)
		{
			deathCamTics++;

			// Fall and Look up
			if (deathCamTics <= 30)
			{
				pitch += (targetPitch - pitch) * 0.15;
			}

			// Wobble
			else if (deathCamTics <= 100)
			{
				double t = deathCamTics - 30;

				pitch = targetPitch + sin(t * 0.15) * 2.5;
				roll  = sin(t * 0.12) * 3.5;

				angle += sin(t * 0.10) * 0.4;
			}

			// Die
			else
			{
				pitch = targetPitch;
				player.mo.angle += (targetYaw - player.mo.angle) * 0.035;
				roll += ((targetRoll * 0.4) - roll) * 0.03;
			}
		}
	}

	void StartDeathCam()
	{
		didDeathCam = true;
		deathCamTics = 0;

		wobbleDir = (Random(0, 1) == 0) ? -1.0 : 1.0;

		targetPitch = -78;                 // almost straight up
		targetYaw   = angle + (35 * wobbleDir);
		targetRoll  = 45 * wobbleDir;
	}
}